<?php

namespace App\Repository;

/**
 * Box
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Box extends \Doctrine\ORM\EntityRepository
{
}
