<?php

namespace App\Repository;

/**
 * TicketType
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketType extends \Doctrine\ORM\EntityRepository
{
}
